version: 2

sources:
  - name: snowflake_sample_data #name of database
    description: 'A sample database provided by sowflake'
    database: snowflake_sample_data
    schema: TPCDS_SF10TCL
    tables:
      - name: store_sales
        description: 'Deatils about store-data'
